### ISSUE TITLE
Hyper missing /opt/Hyper/resources/bin/yarn-standalone.js

### ISSUE THREAD

**Issue by archenroot** [Keepco/gentoo-overlay-seadep#18]
I emerged =x11-terms/hyper-2.0.4, when started as regular user I get few notifications:

1. 
`"hyperline" failed to load in the renderer process. Check Developer Tools for details.`

2.
`Plugin "hyperline" failed to load (Cannot find module '/home/zangetsu/.hyper_plugins/node_modules/hyperline')
`

3.
```
Command failed: /opt/Hyper/hyper /opt/Hyper/resources/bin/yarn-standalone.js install --no-emoji --no-lockfile --cache-folder /home/zangetsu/.hyper_plugins/cache
module.js:472
throw err;
^
Error: Cannot find module '/opt/Hyper/resources/bin/yarn-standalone.js'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at Module.runMain (module.js:605:10)
at run (bootstrap_node.js:431:7)
at startup (bootstrap_node.js:155:9)
at bootstrap_node.js:551:3
Command failed: /opt/Hyper/hyper /opt/Hyper/resources/bin/yarn-standalone.js install --no-emoji --no-lockfile --cache-folder /home/zangetsu/.hyper_plugins/cache
module.js:472
throw err;
^
Error: Cannot find module '/opt/Hyper/resources/bin/yarn-standalone.js'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at Module.runMain (module.js:605:10)
at run (bootstrap_node.js:431:7)
at startup (bootstrap_node.js:155:9)
at bootstrap_node.js:551:3
```

When I tried to start as root from Konsole terminal in KDE plasma I get other additional messages:
```
[Notification] Error loading config: SyntaxError, see DevTools for more info: undefined
Error loading config: .hyper.js:1
[object Object]
        ^^^^^^
SyntaxError: Unexpected identifier
    at _syntaxValidation (/opt/Hyper/resources/app.asar/config/init.js:15:12)
    at _init (/opt/Hyper/resources/app.asar/config/init.js:29:18)
    at exports._import (/opt/Hyper/resources/app.asar/config/import.js:43:15)
    at Object.exports.setup (/opt/Hyper/resources/app.asar/config.js:83:9)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:63:8)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:252:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
plugins have changed / not init, scheduling plugins installation
running in prod mode
electron will open file:///opt/Hyper/resources/app.asar/index.html
[Notification] Error loading config: SyntaxError, see DevTools for more info: undefined

(hyper:10636): libnotify-WARNING **: Failed to connect to proxy

(hyper:10636): libnotify-WARNING **: Failed to connect to proxy

(hyper:10636): libnotify-WARNING **: Failed to connect to proxy
Launching yarn: /opt/Hyper/hyper /opt/Hyper/resources/bin/yarn-standalone.js install --no-emoji --no-lockfile --cache-folder /root/.hyper_plugins/cache
Error: Command failed: /opt/Hyper/hyper /opt/Hyper/resources/bin/yarn-standalone.js install --no-emoji --no-lockfile --cache-folder /root/.hyper_plugins/cache
module.js:472
    throw err;
    ^

Error: Cannot find module '/opt/Hyper/resources/bin/yarn-standalone.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
[Notification] Error updating plugins.: Command failed: /opt/Hyper/hyper /opt/Hyper/resources/bin/yarn-standalone.js install --no-emoji --no-lockfile --cache-folder /root/.hyper_plugins/cache
module.js:472
    throw err;
    ^

Error: Cannot find module '/opt/Hyper/resources/bin/yarn-standalone.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3


(hyper:10636): libnotify-WARNING **: Failed to connect to proxy

(hyper:10636): libnotify-WARNING **: Failed to connect to proxy
```

After about 3 minutes (some network timeout) it started under root as well. Out of the messages for regular user, the hyper starts under regular user directly (no proxy timeouts).

I note that I did a change in hyper.js for regular user to add first plugin:
```
plugins: [
    "hyperline",
  ],
```

Do you plan stabilization of this cool piece of software? I can actually imagine pure JS based desktop on my Gentoo system :D one day.

**Comment by archenroot** [comment]
Regarding missing yarn-standalone.js (3rd notification), to fix it I added into ebuild following line and testing it in the moment:
```
        # Install missing JS artefacts from BIN folder
	local destdir="/opt/Hyper/resources"
	local insdir="${S}"
	insinto $destdir
	doins -r $insdir/bin
```

**Comment by archenroot** [comment]
Following commit fixes issue number 3, the 1 and 2 is related to the plugin actiavation, so not issue with ebuild itself.

https://github.com/archenroot/gentoo-overlay/commit/1a2f17ed729df28416c62cbd32a77f7d8169ce2a

**Comment by Cogitri** [comment]
Actually, if you want to you can keep Hyper in your overlay, I don't use it anymore, so I don't particularly mind :)

**Comment by archenroot** [comment]
:DDD And what do you use? I I use Konsole and now trying this Hyper if will find it any better, I am interested in matrix like scalability (n rows to m columns of terminals on large displays for example) any hint to try? Anyway I did full hardcopy into my overlay, so you can get rid of that if you don't like to maintain it.

Thx

**Comment by Cogitri** [comment]
I use Gnome-Terminal myself, but I use almost everything GNOME, so yeah ^^

Hyper is neat in theory, but in practice it was too slow for my taste ( especially in start up )

**Comment by archenroot** [comment]
Hm, 3-4 seconds on my 2core xps 13 laptop, not sure if on xps 15(4core) will do any better. Understand, I also need reactive desktop, otherwise it gets boring...

**Comment by Cogitri** [comment]
It takes like 1 1/2 seconds on my Ryzen rig, which is too long for a terminal ( IMO ), since I open it a lot, so it gets tiresome over time :/

**Comment by archenroot** [comment]
Yes, I know what you are talking about, I used on few projects Oracle Data
Integrator or other IDE (ok not terminal) and called that development
click-and-wait, you ask you wait, you ask you wait, from those times I have
anything which is not performant in real-time. I would expect more from
hyper as it is Javascript, but povered by Google engine V8, which is known
to be fast... but still probably not that fast or hyper is using too robust
architecture (lot of checks, etc.)

2017-11-02 17:46 GMT+01:00 Rasmus Thomsen <notifications@github.com>:

**Comment by archenroot** [comment]
Latency is simply annoying ...

**Comment by Cogitri** [comment]
I don't think it's actually some checks or V8 being slow, it's just that a lot more stuff has to be loaded for Hyper to start up compared to your usual terminal, Electron ( which alone is bigger than almost all terminals ) has to be loaded, it's plugins and non-system-libs have to be loaded and then, finally, Hyper's JS has to be loaded, so it can't be faster, no matter what.

**Comment by archenroot** [comment]
I also tend to think V8 is not the case, but what I call "robust architecture" (as you say, plugins, libs load, etc.)

From Java world there exists actually a tool called nailgun, http://martiansoftware.com/nailgun/index.html

Instead of tunin JVM switches to speedup the warm-up (which you can still do), it preloads whole application into RAM and when you call it from terminal, it executes directly. I used it a lot, in extreme situation, the systems starts up, nothing is actually running, but 16GB of ram are occupied :-)))))

You can use the same with nodejs:
https://github.com/lucidsoftware/nodegun

which is nailgun for nodejs

**Comment by archenroot** [comment]
This should be deadly fast startup :D, just one point, Marty shared the code base with Facebook, so this is now official repo:
https://github.com/facebook/nailgun

In case of JVM interest, the NodeJS one is correct.
