### ISSUE TITLE
Adopting a few packages

### ISSUE THREAD

**Issue by ghost** [Keepco/gentoo-overlay-seadep#19]
Hello,

I'm interested in adopting some of your packages:
- dev-vcs/gitkraken-bin
- gnome-extra/gnome-pomodoro (already landed)
- media-sound/gmusicproxy (and its dependencies)
  - dev-python/gmusicapi
  - dev-python/gpsoauth
  - dev-python/pycryptodomex
  - dev-python/validictory

Their new home will be the [frabjous](https://github.com/csmk/frabjous) overlay.

**Comment by Cogitri** [comment]
Okay, thanks for notifying me, I'll delete those from my overlay shortly :)

**Comment by ghost** [comment]
`net-im/rambox-bin` is new to me and seems interesting, but I need to read more about it. I'll let you know if I decided to adopt this one too.

Oh, and thank you for your contribution for the Gentoo community so far.

**Comment by ghost** [comment]
All packages (rambox-bin included) have landed. 😃 

Do you wish to be mentioned in the metadata.xml as the original author and retired maintainer?

Something like this:

```xml
<pkgmetadata>
	....
	<maintainer type="person">
		<email>devnull@localhost.invalid</email>
		<name>Rasmus Thomsen</name>
		<description>Original author. Retired maintainer.</description>
	</maintainer>
	....
</pkgmetadata>
```

**Comment by Cogitri** [comment]
Thank you very much for keeping me up-to-date :)

It would be lovely if you mentioned me as maintainer, thanks! 👍 
I guess you can take the email from my github account :)

**Comment by ghost** [comment]
_Wunderbar!_ I will add them in the next commit. ;)

**Comment by ghost** [comment]
Although `hyper` has a new home in archenroot's overlay, I've decided to keep one based on your works.

**Comment by ghost** [comment]
A reworked `hyper` has [landed](https://github.com/csmk/frabjous/tree/master/x11-terms/hyper). 🎉
