### ISSUE TITLE
JRE

### ISSUE THREAD

**Issue by jonasstein** [Keepco/gentoo-overlay-seadep#4]
i think you can drop the complete JRE stuff. Just add an dependency for the right JRE version
https://github.com/Keepco/gentoo-overlay-seadep/blob/master/sci-mathematics/geogebra-bin/geogebra-bin-5.0.309.0.ebuild#L30

**Comment by Cogitri** [comment]
Had this included because I thought it was needed to log into Geogebra, but it seems like Geogebra just needs the jre to be installed with javafx.  Removed it.
