### ISSUE TITLE
cannot emerge =x11-terms/hyper-1.3.1

### ISSUE THREAD

**Issue by archenroot** [Keepco/gentoo-overlay-seadep#6]
npm ERR! Linux 4.10.3-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/portage/x11-terms/hyper-1.3.1/homedir/.npm/_logs/2017-04-24T13_53_57_910Z-debug.log
>>> Source prepared.
>>> Configuring source in /tmp/portage/x11-terms/hyper-1.3.1/work/hyper-1.3.1 ...
>>> Source configured.
>>> Compiling source in /tmp/portage/x11-terms/hyper-1.3.1/work/hyper-1.3.1 ...
npm ERR! Linux 4.10.3-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "pack"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! missing script: pack
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/portage/x11-terms/hyper-1.3.1/homedir/.npm/_logs/2017-04-24T13_53_58_872Z-debug.log
>>> Source compiled.
>>> Test phase [not enabled]: x11-terms/hyper-1.3.1

>>> Install hyper-1.3.1 into /tmp/portage/x11-terms/hyper-1.3.1/image/ category x11-terms
/usr/bin/install: cannot stat 'dist/linux-unpacked/locales': No such file or directory
!!! doins: dist/linux-unpacked/locales does not exist
/usr/bin/install: cannot stat 'dist/linux-unpacked/resources': No such file or directory
!!! doins: dist/linux-unpacked/resources does not exist
 * ERROR: x11-terms/hyper-1.3.1::seadep failed (install phase):
 *   doins failed
 * 
 * If you need support, post the output of `emerge --info '=x11-terms/hyper-1.3.1::seadep'`,
 * the complete build log and the output of `emerge -pqv '=x11-terms/hyper-1.3.1::seadep'`.
 * The complete build log is located at '/tmp/portage/x11-terms/hyper-1.3.1/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/x11-terms/hyper-1.3.1/temp/environment'.
 * Working directory: '/tmp/portage/x11-terms/hyper-1.3.1/work/hyper-1.3.1'
 * S: '/tmp/portage/x11-terms/hyper-1.3.1/work/hyper-1.3.1'
 * QA Notice: file does not exist:
 * 
 * 	doins: dist/linux-unpacked/locales does not exist
 * 	doins: dist/linux-unpacked/resources does not exist

**Comment by Cogitri** [comment]
Should be fixed by 8313ae5afe3fd3fa1f48f802308f7037443ee063 . I also added `die` to a few of npms operations, to make sure that portage doesn't try to continue building hyper if npm failed. Thanks for reporting!
